name: Create a new release of the overlay
on: workflow_dispatch
jobs:
  prepare-release:
    name: Prepare the release
    runs-on: ubuntu-latest
    steps:
      - name: Download the repo
        uses: actions/checkout@v4
      - name: Get the overlay version
        run: |
            echo "OVERLAY_VERSION=$(cat metadata.txt | grep "Version: " | cut -c 10-)" >> $GITHUB_ENV
      - name: Put the repo into the ZIP archive
        run: |
          cd ../
          rm -rf HitErrorMeter.by.KapiWilq.zip
          cp -r HitErrorMeter HitErrorMeter\ by\ KapiWilq
          zip -r HitErrorMeter.by.KapiWilq.zip HitErrorMeter\ by\ KapiWilq -x ".git/*" ".github/*" "README.md"
      - name: Publish a new release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.OVERLAY_VERSION }}
          tag_name: v${{ env.OVERLAY_VERSION }}
          token: ${{ secrets.GITHUBPAT }}
          fail_on_unmatched_files: true
          files: HitErrorMeter.by.KapiWilq.zip
          make_latest: true

